### ISSUE TITLE
textures as "missing"

### ISSUE THREAD

**Issue by SnowTeaGD** [HJfod/BetterEdit#18]
So i downloaded this and it said that the textures are missing
I placed all the textures in the Resources folder, and it was the same thing.

**Comment by HJfod** [comment]
Old issue but still commenting because this is still common.
Make sure you have placed all of the .png **and** .plist files in the Resources folder.
This can be fixed by using the Refresh Textures features in MHv7 or changing texture quality from High to Medium and then back to High (or vice versa if you use Medium or Low graphics)

**Comment by s0meone247** [comment]
I still have this issue and readded all the files. using gdhm
