### ISSUE TITLE
Mabye?

### ISSUE THREAD

**Issue by GDINKIFy** [HJfod/BetterEdit#247]
You could make it so the slabs line back up for anyone using the mod, and by the slabs I mean the ones that are like 3 pixels off, or you could also make it so it shows what percentage you are into the level above the slider at the top that make scrolls through the level.

**Comment by ghost** [comment]
Please stick to one suggestion at a time - this is why the template is set up the way it is.

- Resizing the 'slab'-type blocks to be exactly half a block in size is outside the scope of BetterEdit for exactly the reason you mentioned - it would only work for people with the mod.
- The level percentage thing is a good suggestion and was present in 2.1, but may be difficult (though not impossible?) in 2.2 due to gameplay rotations. Please make a new issue for this and use the template appropriately.
