### ISSUE TITLE
Controller not working...

### ISSUE THREAD

**Issue by DarkSansGD** [HJfod/BetterEdit#9]
Weird issue, but I am a controller player so naturally I'm trying to use my controller to preview or playtest levels in GD, but when I download this plugin, all functionality from my controller ceases to be.

**Comment by HJfod** [comment]
Hello!

This issue has been raised multiple times on the Discord server, and I know what the cause is. BetterEdit rewrites the entire keybind system for GD in order to support customizing keyboards, and as such all default keybinds in the Editor and while playing levels have to be redefined in code. Unfortunately, I do not own a controller myself, and I have no clue what the controller buttons are represented as in-game. I know they're some keycode, but no one has told me yet what.

For now, a fix should just be manually setting the controller buttons in the keybinds menu. (If it works, please send me your `BEKeybindManager.dat` file so I can finally figure out what the hell the controller buttons are.)

**Comment by DarkSansGD** [comment]
Will do, I'm going to attempt to find out what they are internally first so
I can get an idea of what to look for in the code of Geometry Dash.

**Comment by Saturnflyer567** [comment]
It turns out you can't set A as your p1 input.

**Comment by Saturnflyer567** [comment]
It turns out you can't set A as your p1 input.

**Comment by DarkSansGD** [comment]
There’s no way, I don’t believe that.DarkSans -On Aug 25, 2023, at 5:51 PM, Saturnflyer567 ***@***.***> wrote:﻿
It turns out you can't set A as your p1 input.
